before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

dockers:
  - image_templates:
    - "docker.io/cloudputation/iterator:latest"
    - "docker.io/cloudputation/iterator:{{ .Major }}"
    - "docker.io/cloudputation/iterator:{{ .Major }}.{{ .Minor }}"
    - "docker.io/cloudputation/iterator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"

    build_flag_templates:
    - "--pull"
    # OCI annotations: https://github.com/opencontainers/image-spec/blob/main/annotations.md
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
release:
  github:
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append
changelog:
  skip: true
